### ISSUE TITLE
too much bug report templates

### ISSUE THREAD

**Issue by Chupsy** [Najet29/Issue-Tracker#3]
**Describe the bug**
There seems to be way to much bug templates, we don't know which one to use. I talked about it in another issue, but no comment was given to me.

**To Reproduce**
1. Go to 'Issues'
2. Click on 'New issue'

**Expected behavior**
We should have only one bug template, or at least proper names of templates.

**Screenshots**
![Capture d’écran 2019-07-10 à 16 35 30](https://user-images.githubusercontent.com/3929330/60978107-ef4bf100-a330-11e9-8c3d-80b75e49abce.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 75

**Comment by Najet29** [comment]
Thank you @Chupsy 
I will create also a template named "Reporting CA". If u could take a look on it, that will be great !
