### ISSUE TITLE
Réinitialisation du mot de passe 

### ISSUE THREAD

**Issue by Najet29** [Najet29/Issue-Tracker#4]
**Describe the bug**
Lorsque blablablabla 

**To Reproduce**
1. Go to blablabla 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chupsy** [comment]
Bonjour Najet, vous etes proprietaire de ce projet, avez-vous vraiment besoin de vous envoyer un ticket vous-meme ?
cordialement
