### ISSUE TITLE
Wtf ????

### ISSUE THREAD

**Issue by Deftunk** [Najet29/Issue-Tracker#5]
**Describe the bug**
J'ai cru voir Najet sur github. C'est incomprehensible. Vous vous foutez de la gueule du monde chez Issue-Tracker !

**To Reproduce**
1. Go to [Github](https://github.com)
2. Searh for "Najet29" in search bar on top
3. Press enter

**Expected behavior**
When i look for Najet on github, there is no results...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser chrome, safari
 - Version 75

**Additional context**
Bonjour Najet

**Comment by Najet29** [comment]
@Deftunk 
Thank you for your contribution.
I have an other issue with the new "support" role you gave for the Groups (PDN Groupe for example). 
How can I track what had be done by the real support team ?

Additional context : 
Bonjour Martin

**Comment by Deftunk** [comment]
@Najet29 
C'est quoi ta question ? J'ai pas bien compris.
En vrai t'es en train d'essayer de détourner Github pour traquer des customer issues ?

**Comment by Najet29** [comment]
Je te taquinais ! Sur la feature support chez vous !!
Banane !

**Comment by Deftunk** [comment]
![giphy](https://user-images.githubusercontent.com/11680163/60979811-a47fa880-a333-11e9-8a79-6e71b1a0df49.gif)
