### ISSUE TITLE
En fait il faut que tu utilises l'issue tracker sur les projets des devs

### ISSUE THREAD

**Issue by Deftunk** [Najet29/Issue-Tracker#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chupsy** [comment]
hi martin,
this is an english environment, please use english.
Thank you.

**Comment by Deftunk** [comment]
omfg... Damn... My bad... sry guys... i'm unforgivable... Please let me know if we are ok... Je parle français.

**Comment by Najet29** [comment]
It's Britney bitch
